steps:
- name: gcr.io/cloud-builders/gcloud
  args:
  - functions
  - deploy
  - yt-download-consumer
  id: "deploy-cloudfunc-yt-url-consumer"
  dir: functions/yt-url-consumer
options:
  logging: CLOUD_LOGGING_ONLY
