steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud functions deploy go-firestore-typesense-syncer \
      --entry-point=IndexOnWrite \
      --runtime=go122 \
      --region=us-west2 \
      --source=. \
      --gen2
  id: "deploy-cloudfunc-go-firestore-typesense-syncer"
  dir: functions/go-firestore-typesense-syncer
options:
  logging: CLOUD_LOGGING_ONLY
