steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "$$CREDENTIALS_JSON" > credentials_firebase.json &&
    echo "$$CREDENTIALS_PUBSUB_JSON" > credentials_pub_sub.json &&
    gcloud functions deploy transcript-api \
      --entry-point=transcript_api \
      --runtime=python39 \
      --region=us-central1 \
      --source=transcript-api \
      --gen2
  secretEnv: ['CREDENTIALS_JSON', 'CREDENTIALS_PUBSUB_JSON']
  id: "deploy-cloudfunc-transcript-api"
options:
  logging: CLOUD_LOGGING_ONLY
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/credentials_json/versions/latest
    env: 'CREDENTIALS_JSON'
  - versionName: projects/$PROJECT_ID/secrets/credentials_pub_sub_json/versions/latest
    env: 'CREDENTIALS_PUBSUB_JSON'
    