steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "$$CREDENTIALS_JSON" > credentials_firebase.json &&
    echo "$$CREDENTIALS_PUBSUB_JSON" > credentials_pub_sub.json &&
    gcloud functions deploy go-publish-ids \
      --entry-point=PubMissingIds \
      --runtime=go122 \
      --region=us-central1 \
      --source=functions/go-publish-ids \
      --gen2
  env:
  - 'DATABASE_ID=${_DATABASE_ID}'
  - 'DOCUMENT_PATH=${_DOCUMENT_PATH}'
  - 'PROJECT_ID=${_PROJECT_ID}'
  secretEnv: ['CREDENTIALS_JSON', 'CREDENTIALS_PUBSUB_JSON']
  id: "deploy-cloudfunc-go-publish-ids"
options:
  logging: CLOUD_LOGGING_ONLY
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/credentials_json/versions/latest
    env: 'CREDENTIALS_JSON'
  - versionName: projects/$PROJECT_ID/secrets/credentials_pub_sub_json/versions/latest
    env: 'CREDENTIALS_PUBSUB_JSON'
    