steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "$$CREDENTIALS_PUBSUB_JSON" > credentials_pub_sub.json &&
    gcloud functions deploy consume-batched-urls \
      --entry-point=ConsumeBatchedUrls \
      --runtime=go122 \
      --region=us-central1 \
      --gen2
  secretEnv: ['CREDENTIALS_PUBSUB_JSON']
  id: "deploy-cloudfunc-consume-batched-urls"
  dir: functions/consume-batched-urls
options:
  logging: CLOUD_LOGGING_ONLY
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/credentials_pub_sub_json/versions/latest
    env: 'CREDENTIALS_PUBSUB_JSON'