name: CI and Trigger Cloud Build on Change to yt-url-consumer

on:
  push:
    branches:
      - dien/gf-yt-downloader
    paths:
      - 'functions/yt-url-consumer/**'

jobs:
  prepare-and-trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # TODO: Unit tests
      
      - name: Populate Credentials for Cloud Function
        run: |
          cat << EOF > functions/yt-url-consumer/credentials.json
          {
            "type": "service_account",
            "project_id": "scriptsearch",
            "private_key_id": "${{ secrets.SERVICE_ACCOUNT_PRIVATE_KEY_ID }}",
            "private_key": "${{ secrets.SERVICE_ACCOUNT_PRIVATE_KEY }}",
            "client_email": "${{ secrets.SERVICE_ACCOUNT_EMAIL }}",
            "client_id": "${{ secrets.SERVICE_ACCOUNT_ID }}",
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
            "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/${{ secrets.SERVICE_ACCOUNT_EMAIL }}",
            "universe_domain": "googleapis.com"
          }
          EOF
      
      - name: Trigger Cloud Build
        run: |
          curl -f POST "${{ secrets.CLOUD_BUILD_WEBHOOK_URL }}" \
          -H "Content-Type: application/json" \
          -d '{"branch": "dien/gf-yt-downloader"}'
