name: CI and Trigger Cloud Build on Change to yt-url-consumer

on:
  push:
    branches:
      - dien/gf-yt-downloader
    paths:
      - 'functions/yt-url-consumer/**'

jobs:
  prepare-and-trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # TODO: Unit tests
      
      - name: Trigger Cloud Build
        run: |
          curl -f POST "${{ secrets.CLOUD_BUILD_WEBHOOK_URL }}" \
          -H "Content-Type: application/json" \
          -d '{"branch": "dien/gf-yt-downloader"}'
