name: CI and Trigger Cloud Build on Change for go-publish-ids

on:
  push:
    branches:
      - main
    paths:
      - 'functions/go-publish-ids/**'

jobs:
  prepare-and-trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # TODO: Unit tests
      
      - name: Trigger Cloud Build
        run: |
          curl -f POST "${{ secrets.CLOUD_BULD_GO_PUBLISH_IDS_WEBHOOK_URL }}" \
          -H "Content-Type: application/json" \
          -d '{"branch": "main"}'
